# Generated by Django 3.2.16 on 2023-01-12 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукти'},
        ),
    ]
